version: '3.8'

services:
  devpro.api:
    build:
      args:
        - ASPNETCORE_ENVIRONMENT=Production
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5300:5300"
      - "7300:7300"
    volumes:
      - ./appsettings.Production.json:/app/appsettings.Production.json