apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devpro-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - devops.microwe.net
    secretName: devpro-tls
  rules:
  - host: devops.microwe.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devpro-service
            port:
              number: 80
