apiVersion: v1
kind: Service
metadata:
  name: devpro-service
spec:
  type: NodePort                # Change from ClusterIP to NodePort
  selector:
    app: devpro                # Ensure this matches your deployment labels
  ports:
    - protocol: TCP
      port: 80                 # Service port
      targetPort: 80           # Container port
      nodePort: 30080          # NodePort, must be between 30000-32767
